### ISSUE TITLE
Is it possible to offset a mesh preserving its sharp edges?

### ISSUE THREAD

**Issue by Another-Anonymous-User** [mlivesu/cinolib#148]
Having a 3D triangular surface mesh is it possible to offset it by a specified distance preserving its sharp edges with cinolib?

**Comment by mlivesu** [comment]
are we talking about a planar mesh that you want to extrude along the third dimension or a closed surface mesh that encloses a volume?

**Comment by Another-Anonymous-User** [comment]
It would be a closed surface mesh

**Comment by mlivesu** [comment]
ok. So currently there is no self-contained solution to your problem in the library, but you can kind of bake it. The actual offsetting is pretty trivial, it can be formulated as a motion of each surface vertex along its normal direction by a constant quantity, something like

```c++
std::vector<cinolib::vec3d> normals = m.vector_vert_normals();
double delta = m.bbox().diag()*0.01;
for(uint vid=0; vid<m.num_verts(); ++vid)
{
      m.vert(vid) += normals[vid] * delta;
}
```

The complex part comes afterwards, because these motions can create any sort of self compenetration, making the output solid ill-defined. This may or may not be an issue for you application. In case it is, you can remove all such intersections using a recent algorithm of mine that is not (yet) included in cinolib. Code is [here](https://github.com/gcherchi/FastAndRobustMeshArrangements). 

Note that this latter step will leave (conforming) garbage inside your mesh. The output can be cleaned with some marching algorithm that start from the outside and walks on the outer surface, ignoring the inner pieces. Once you have the arrangement it's not complex do it, but I don't have code for it right now.

**Comment by Another-Anonymous-User** [comment]
Thanks, I will give it a try!! The 'not yet included' code should be very helpful. Regarding simply offsetting along the normals, won't this lead to the rounding of convex sharp edges?

**Comment by mlivesu** [comment]
mmm no, what I propose would not blur edges. Creases will remain sharp, but the distance from the reference surface is not constant. keep in mind that precisely maintaining the same exact distance everywhere conflicts with your aim to not blur sharp edges, the two requirements cannot be fulfilled together

**Comment by Another-Anonymous-User** [comment]
My bad, if distance from the reference is not constant I completely agree the edges can be preserved. The confusion on my side came because you said "along its normal direction by a constant quantity". Thank you once again! :)
