### ISSUE TITLE
Interactive Selection in the viewer

### ISSUE THREAD

**Issue by 461353349** [mlivesu/cinolib#26]
If the selected elements could be shown or hidden, The inside of the model could be seen. It is useful for some applications. Will cinolib add the mouse selction api or functions? For example
1) Interactive rectangle selection of nodes or elements;
2) Hiding the selected nodes and elements.
![image](https://user-images.githubusercontent.com/22976548/68991808-c1a62400-089d-11ea-95bd-81f393d4c7fc.png)

**Comment by mlivesu** [comment]
Hi, CinoLib is meant to provide basic ingredients to build research oriented software prototypes. To this end, the functionalities you mention are not strictly contained in the library, but all the ingredients are available, so that you can implement them with a few lines of code. As a representative example, I am attaching at the bottom of this message a simple implementation of the mouse_click callback which would allow you to show/hide a selected element from a volumetric mesh, such as the one shown in the picture above. To try it out you can literally copy/paste such code in the library examples, and play it.

A few extra notes on this tool:

 - the {vert/edge/face/poly}_pick facilities are implemented in the most trivial possible way, so they run in O(n) with n being the number of elements. This is usually OK for user interaction and medium sized meshes. Should you need more speed, you can always use a cinolib::Octree, and the ray intersection query to obtain more accurate items selection at a much faster speed.

 - the selection of all the elements inside a box drawn in the canvas could be easily generated starting from my example. In that case you should implement the mouse_press/mouse_release callbacks for the generation of the wanted rectangular selection. The rest is not significantly different from the code I am sharing with you

Good luck!

    gui.callback_mouse_press = [&](GLcanvas *c, QMouseEvent *e)
    {
        if(e->modifiers() == Qt::ControlModifier)
        {
            vec3d p;
            vec2i click(e->x(), e->y());
            if (c->unproject(click, p))
            {
                uint pid = m.pick_poly(p);
                m.poly_data(pid).visible = false;
                m.updateGL();
                c->updateGL();
            }
        }
        else if(e->modifiers() == Qt::ShiftModifier)
        {
            vec3d p;
            vec2i click(e->x(), e->y());
            if(c->unproject(click, p))
            {
                uint fid = m.pick_face(p);
                for(uint pid : m.adj_f2p(fid)) m.poly_data(pid).visible = true;
                m.updateGL();
                c->updateGL();
            }
        }
    };

**Comment by 461353349** [comment]
I see! 
Thank you very much!!!

**Comment by yvanblanchard** [comment]
Hello @mlivesu 

could you please give an up-to-date sampel code for doing this without Qt (but GLFW instead) ?
I tried this, but the 'visible' attribute is no longer available:

![image](https://github.com/mlivesu/cinolib/assets/63931618/15264cc7-2089-4781-8c31-f2f62d44dda2)
